version: "3.7"
services:
  postgres:
    image: library/postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Password1
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8180:8080
    environment:
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Password1
      DB_DATABASE: postgres
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: Password1
    links:
      - postgres
    depends_on:
      - postgres
  arangodb:
    image: arangodb/arangodb:latest
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: Password1
  content-server:
    image: docker.pkg.github.com/rich43/archesky-content-server/archesky-content-server:0.0.${CONTENT_SERVER_RELEASE}-snapshot
    ports:
      - 8080:8080
      - 8443:8443
    links:
      - arangodb
      - auth-server
    depends_on:
      - arangodb
      - auth-server
    environment:
      arangodb.host: arangodb
      archesky.auth.library.server.url: https://auth-server:9443/graphql
  auth-server:
    image: docker.pkg.github.com/rich43/archesky-auth-server/archesky-auth-server:0.0.${AUTH_SERVER_RELEASE}-snapshot
    ports:
      - 9090:9090
      - 9443:9443
    links:
      - keycloak
    depends_on:
      - keycloak
    environment:
      openid.connect.certificate.url: http://keycloak:8080/auth/realms/Archesky/protocol/openid-connect/certs
      openid.connect.issuer: http://localhost:8180/auth/realms/Archesky
