version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: library/postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Password1
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8180:8080
    environment:
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Password1
      DB_DATABASE: postgres
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: Password1
      KEYCLOAK_IMPORT: /keycloak/archesky.json
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./keycloak:/keycloak
  arangodb:
    image: arangodb/arangodb:latest
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: Password1
  content-server:
    image: docker.pkg.github.com/rich43/archesky-content-server/archesky-content-server:0.0.${CONTENT_SERVER_RELEASE}-snapshot
    ports:
      - 8080:8080
    links:
      - arangodb
      - auth-server
      - kafka
      - zookeeper
    depends_on:
      - arangodb
      - auth-server
      - kafka
      - zookeeper
    environment:
      arangodb.host: arangodb
      archesky.auth.library.server.url: http://auth-server:9090/graphql
  auth-server:
    image: docker.pkg.github.com/rich43/archesky-auth-server/archesky-auth-server:0.0.${AUTH_SERVER_RELEASE}-snapshot
    ports:
      - 9090:9090
    links:
      - keycloak
    depends_on:
      - keycloak
    environment:
      openid.connect.certificate.url: http://keycloak:8080/auth/realms/Archesky/protocol/openid-connect/certs
      openid.connect.issuer: http://localhost:8180/auth/realms/Archesky
