version: "3.7"
services:
  arangodb:
    image: arangodb/arangodb:latest
    ports:
      - 7529:8529
    environment:
      ARANGO_ROOT_PASSWORD: Password1
  chat-server:
    image: docker.io/pynguins/archesky-chat-server:latest
    ports:
      - 6060:8080
    links:
      - arangodb
    depends_on:
      - arangodb
    environment:
      arangodb.host: arangodb
    networks:
      - traefik
  chat-client:
    image: docker.io/pynguins/chat-client:latest
    ports:
      - 5050:80
    links:
      - chat-server
    depends_on:
      - chat-server
    environment:
      CHAT_SERVER_HOST: chat-server
    labels:
      traefik.frontend.rule: Host:chat.pynguins.com
    networks:
      - traefik
networks:
  traefik:
