version: "3.7"
services:
  arangodb:
    image: arangodb/arangodb:latest
    ports:
      - 7529:8529
    environment:
      ARANGO_ROOT_PASSWORD: Password1
  chat-server:
    image: docker.pkg.github.com/rich43/archesky-chat-server/archesky-chat-server:0.0.${CHAT_SERVER_RELEASE}-snapshot
    ports:
      - 6060:8080
    links:
      - arangodb
    depends_on:
      - arangodb
    environment:
      arangodb.host: arangodb
  chat-client:
    image: docker.pkg.github.com/rich43/chat-client/chat-client:0.0.${CHAT_CLIENT_RELEASE}-snapshot
    ports:
      - 5050:80
    links:
      - chat-server
    depends_on:
      - chat-server
    environment:
      CHAT_SERVER_HOST: chat-server
