apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: arangodb
  name: arangodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: arangodb
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.service: arangodb
    spec:
      containers:
        - env:
            - name: ARANGO_ROOT_PASSWORD
              value: Password1
          image: arangodb/arangodb:latest
          imagePullPolicy: ""
          name: arangodb
          ports:
            - containerPort: 8529
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
