apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: auth-server
    spec:
      containers:
      - env:
        - name: openid.connect.certificate.url
          value: http://keycloak:8080/auth/realms/archesky_%s/protocol/openid-connect/certs
        - name: openid.connect.issuer
          value: http://localhost:3000/auth/realms/archesky_%s
        image: docker.pkg.github.com/rich43/archesky-auth-server/archesky-auth-server:0.0.283094786-snapshot
        imagePullPolicy: ""
        name: auth-server
        ports:
        - containerPort: 9090
        - containerPort: 9443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
