apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak-server
  name: keycloak-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak-server
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.service: keycloak-server
    spec:
      containers:
        - env:
            - name: DB_ADDR
              value: postgres-server
            - name: DB_DATABASE
              value: postgres
            - name: DB_PASSWORD
              value: Password1
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: KEYCLOAK_PASSWORD
              value: Password1
            - name: KEYCLOAK_USER
              value: root
          image: jboss/keycloak:latest
          imagePullPolicy: ""
          name: keycloak-server
          ports:
            - containerPort: 8080
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
