apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres-server
  name: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-server
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.service: postgres-server
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: Password1
          image: library/postgres:latest
          imagePullPolicy: ""
          name: postgres-server
          ports:
            - containerPort: 5432
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
